### ISSUE TITLE
Offline FTPs still appear in search results

### ISSUE THREAD

**Issue by Expyron** [bbc2/porygon-ftp#1]
For example, on porygon.rez, with the search "avi", results from kyo.rez (which is currently offline) appear.

**Comment by bbc2** [comment]
Yes. I will prevent them from appearing in search results in the future.

However, it might be desirable to search offline FTPs though it should not be the default behaviour. I will probably enable users to search those (excluding the very old ones anyway because they are unlikely to reappear).

Thanks for reporting that. I would forget to improve my software otherwise. :)

**Comment by bbc2** [comment]
You can now choose whether to include results from offline servers.  Besides, servers that have been offline for too much time are forgotten.
